"""
ecflowbuilder.py

Defines ECFLOWXMLBuilder, a class for constructing ECFLOW-compatible XML workflows
from modular YAML configurations used in UFS regression testing.

Structure:
- <suite>: Root element
- <family>: Represents each build block
- <task>: Represents each test
- <edit>: Injects environment variables
- <trigger>: Defines dependencies
- <defstatus>: Controls task startup
- <limit>: Restricts concurrency
- <label>, <meter>: GUI metadata and progress tracking

Author: Jong Kim
"""

import yaml
import xml.etree.ElementTree as ET
import os
import re

def resolve_env_vars(value: str) -> str:
    """
    Resolves environment variables in a string of the form ${VAR}.

    Args:
        value (str): Input string with optional ${VAR} patterns.

    Returns:
        str: String with environment variables substituted.
    """
    if not isinstance(value, str):
        return ""
    pattern = re.compile(r"\$\{(\w+)\}")
    return pattern.sub(lambda m: os.environ.get(m.group(1), m.group(0)), value)

class ECFLOWXMLBuilder:
    """
    Builds an ECFLOW XML workflow from a YAML configuration.

    Attributes:
        machine (str): Target machine name.
        rt_yaml (dict): Runtime YAML configuration.
        baseline_config (dict): Baseline setup configuration.
        project (Optional[str]): Optional project filter.
        filter_tests (Optional[set]): Optional set of test_name_compiler strings to include.
        root (Element): Root XML element for the suite.
    """

    def __init__(self, machine, rt_yaml, baseline_yaml, project=None, filter_tests=None):
        """
        Initializes the ECFLOWXMLBuilder.

        Args:
            machine (str): Target machine name.
            rt_yaml (dict or str): Parsed YAML dictionary or path to YAML file.
            baseline_yaml (str): Path to baseline_setup.yaml.
            project (Optional[str]): Optional project filter.
            filter_tests (Optional[set]): Optional set of test_name_compiler strings to include.
        """
        self.machine = machine
        self.project = project
        self.filter_tests = filter_tests
        self.rt_config = rt_yaml if isinstance(rt_yaml, dict) else yaml.safe_load(open(rt_yaml))
        self.baseline_config = yaml.safe_load(open(baseline_yaml))
        self.root = ET.Element("suite", attrib={"name": "ufs_regression"})

    def _add_family(self, key, block):
        """
        Adds a <family> element for a build block.

        Args:
            key (str): Unique identifier for the block.
            block (dict): Block configuration with build and tests.
        """
        compiler = block.get("build", {}).get("compiler", "unknown").lower()
        family = ET.SubElement(self.root, "family", name=key)

        # Compile task
        compile_task = ET.SubElement(family, "task", name=f"compile_{key}")
        ET.SubElement(compile_task, "edit", name="COMPILER", value=compiler)
        ET.SubElement(compile_task, "edit", name="OPTION", value=block.get("build", {}).get("option", ""))
        ET.SubElement(compile_task, "defstatus").text = "queued"
        ET.SubElement(family, "limit", name="compile_limit", value="2")

        # Test tasks
        for test in block.get("tests", []):
            for test_name, test_cfg in test.items():
                if self.project and ("project" not in test_cfg or self.project not in test_cfg["project"]):
                    continue
                if self.filter_tests and f"{test_name}_{compiler}" not in self.filter_tests:
                    continue

                task = ET.SubElement(family, "task", name=test_name)
                ET.SubElement(task, "trigger").text = f"compile_{key} == complete"
                ET.SubElement(task, "defstatus").text = test_cfg.get("defstatus", "queued")

                # Environment variables
                env = test_cfg.get("env", {})
                for var, val in env.items():
                    ET.SubElement(task, "edit", name=var, value=str(val))

                # Labels
                ET.SubElement(task, "label", name="test_name", value=test_name)
                ET.SubElement(task, "label", name="compiler", value=compiler)

                # Meter
                if "meter" in test_cfg:
                    m = test_cfg["meter"]
                    ET.SubElement(task, "meter", name=m["name"], minimum=str(m["min"]), maximum=str(m["max"]), value="0")

                # Optional limit
                if "limit" in test_cfg:
                    ET.SubElement(task, "limit", name=test_cfg["limit"], value="1")

    def generate(self):
        """
        Generates the XML structure by adding families and tasks.
        """
        self.root.insert(0, ET.Comment("Generated by ECFLOWXMLBuilder"))
        for key, block in self.rt_config.items():
            self._add_family(key, block)

    def write(self, output_path: str):
        """
        Writes the generated XML to a file with resolved entities.

        Args:
            output_path (str): Path to output XML file.
        """
        self._indent(self.root)
        xml_str = ET.tostring(self.root, encoding="unicode")
        with open(output_path, "w") as f:
            f.write('<?xml version="1.0" encoding="utf-8"?>\n')
            f.write(xml_str)

    def _indent(self, elem, level=0):
        """
        Indents XML elements for pretty printing.

        Args:
            elem (Element): XML element to indent.
            level (int): Current indentation level.
        """
        i = "\n" + level * "  "
        if len(elem):
            if not elem.text or not elem.text.strip():
                elem.text = i + "  "
            for child in elem:
                self._indent(child, level + 1)
            if not elem.tail or not elem.tail.strip():
                elem.tail = i
        else:
            if level and (not elem.tail or not elem.tail.strip()):
                elem.tail = i
