name: Project Board Updates
on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
  repository_dispatch:
    types: [add-to-project, label-project]

  #schedule:
    #- cron: "1 * * * *"

jobs:
  add-to-project:
    name: Add pull request to project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          #project-url: https://github.com/orgs/ufs-community/projects/70
          project-url: https://github.com/orgs/NOAA-EPIC/projects/18
          github-token: ${{ secrets.PR_PROJECT_TOKEN }}
  label-project:
    name: Update project with labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Baseline changes
        if: github.event.label.name == 'Baseline Updates' || github.event.label.name == 'New Baselines'
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/orgs/ufs-community/projects/70
          github-token: ${{ secrets.GITHUB_TOKEN }}
          field-name: 'Baseline Changes'
          field-value: 'Yes'
      - name: No baseline changes
        if: github.event.label.name == 'No Baseline Change'
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/orgs/ufs-community/projects/70
          github-token: ${{ secrets.GITHUB_TOKEN }}
          field-name: 'Baseline Changes'
          field-value: 'No'
