name: Regression Resource Check

on:
  pull_request_target: # Only works when in the default branch (can work on others as long as also in default branch)
    types: 
      - opened
      - reopened 
      - labeled
      - unlabeled
      - synchronize
# Need to add push logic to call API properly! Workflow assumes a PR, but there isn't one on push to develop...

permissions:
  contents: write

defaults:
  run:
    shell: bash -eo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MACHINES: "acorn derecho gaeac6 hercules orion ursa wcoss2"
  #BASE_URL: https://api.github.com/repos/ufs-community/ufs-weather-model
  BASE_URL: https://api.github.com/repos/NOAA-EPIC/ufs-weather-model
  PR_NUM: ${{ github.event.number }}
  PNG_TOKEN: ${{ secrets.PNG_TOKEN }}

jobs:
  get-data:  
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout feature branch
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          pip install requests numpy matplotlib
          mkdir -p data
      - name: Cache machine stats
        id: cache-stats
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/data
          key: hist-stats-${{ github.event.pull_request.base.sha }} # If develop gets updated, data from repo should, too
      - name: Set data env var (if cache hit) and compare w/HEAD of develop 
        if: steps.cache-stats.outputs.cache-hit == 'true'
        run: |
          echo "TEST_STATS=${{ github.workspace }}/data" >> $GITHUB_ENV
          python -m tests-dev.scripts.get_data
        env: 
          TEST_STATS: ${{ github.workspace }}/data
      - name: Get historical data and compare w/HEAD of develop
        if: steps.cache-stats.outputs.cache-hit != 'true'
        run: |
          mkdir -p data
          python -m tests-dev.scripts.get_data
      - name: Upload json files
        uses: actions/upload-artifact@v7
        with: 
          name: data
          path: ${{ github.workspace }}/data
  wiki-push:
    runs-on: ubuntu-latest
    needs: get-data
    if: github.event.label.name == 'update-wiki-pngs'
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          pip install numpy matplotlib
      - name: Download data
        uses: actions/download-artifact@v8
        with: 
          name: data
          path: data
      - name: Store data location
        run: |
          echo "PLOT_DATA=${{ github.workspace }}/data" >> $GITHUB_ENV
      - name: Create plots
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p plots
          python -m tests-dev.scripts.create_images
      - name: Clone wiki
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}.wiki 
          path: wm-wiki 
          token: ${{ secrets.PNG_TOKEN }} 
      - name: Copy plots to wiki
        if: env.PR_NUM != '' # Still needed? 
        run: |
          cd wm-wiki
          if [[ ! -d "plots" ]]; then
            mkdir -p plots
          fi
          echo $PR_NUM
          cd plots
          cp $GITHUB_WORKSPACE/plots/* .
      - name: Push images to wiki
        run: |
          cd wm-wiki

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          echo "added plots to wm-wiki"
          
          status=`git status -s`

          if [ -z "${status}" ]; then
            echo "Nothing to commit."
          else
            git commit -m "Auto-add plots to wiki"
            git push origin master
          fi
  write-results:  
    runs-on: ubuntu-latest
    needs: get-data
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          pip install pandas mdutils numpy matplotlib
      - name: Download test results
        uses: actions/download-artifact@v8
        with: 
          name: data
          path: ${{ github.workspace }}/data
      - name: Write results summary
        run: |
          python -m tests-dev.scripts.write_test_summary >> $GITHUB_STEP_SUMMARY
        env: 
          RUNTIME_RESULTS: ${{ github.workspace }}/data/runtime_results.json
          MEMORY_RESULTS: ${{ github.workspace }}/data/memory_results.json
